### ISSUE TITLE
Next Coin button behaving unexpectedly.

### ISSUE THREAD

**Issue by Tramp420** [bitcobblers/multiminer#279]
## Expected Behavior

Next coin in the list.

## Current Behavior

Next coin of its own choosing.  #skynet

## Steps to Reproduce

[Watch dis voodoo](https://clipchamp.com/watch/t6DBJNymK3N)

## Possible Solution (Not obligatory)

idk.. y'all are the evil geniuses. :)

## Context

I am now extremely depressed.

## Your Environment

- Operating System : W11
- Application Version : Current
- Mining Application (if applicable) : trex

**Comment by mvastarelli** [comment]
Hah.  This is actually by design.  We should probably have documented it better.  In order to make sure that all coins have equal probability of running we pick a new coin at random from the configured list whenever the user clicks 'Next Coin'.  Otherwise it would be easy to starve coins further down the list since they may never get a chance to run.  We don't want the user to be at the mercy of the app though which is why you can start pick any coin on the list and explicitly tell it to mine that coin.

@evan-cohen What are your thoughts on making this overridable so that users have more control over how coin selection works?  How about a drop-down of strategies?

**Comment by mvastarelli** [comment]
Tracking in #37 

Going to make coin selection configurable.  The two strategies will be either sequential or AI-driven.  

@Tramp420 AI-driven mode will be named `skynet` in your honor.
